### ISSUE TITLE
Spring Boot 2 (Spring 5): Cannot resolve PropertyFilter with id 'antPathFilter'

### ISSUE THREAD

**Issue by mpscheidt** [Antibrumm/jackson-antpathfilter#14]
Using Spring Boot 2.0.4.RELEASE, which is based on Spring 5.0.8.RELEASE.

When following the instructions to setup the AntPathFilter for "Spring 4.2.2+", that is, extending `DelegatingWebMvcConfiguration`, then an exception occurs in cases when the AntPathFilter should _not_ be applied. (The problem is somewhat similar to [this post on SO](https://stackoverflow.com/q/9382094/606662).) Things work fine for controller methods that apply the AntPathFilter for serialization of their response body.

This configuration creates problems for controllers that do not apply the AntPathFilter:

```
@Configuration
public class WebConfig extends DelegatingWebMvcConfiguration {
    @Override
    public void configureMessageConverters(final List<HttpMessageConverter<?>> messageConverters) {
        // Add a MappingJackson2HttpMessageConverter so that
        // objectMapper.writeFiltered
        // is using the objectMapper configured with the needed Mixin
        ObjectMapper objectMapper = Jackson2ObjectMapperBuilder
            .json()
            .mixIn(Object.class, AntPathFilterMixin.class)
            .build();
        messageConverters.add(new MappingJackson2HttpMessageConverter(objectMapper));
        addDefaultHttpMessageConverters(messageConverters);
    }
}
```

When a controller doesn't use the AntPathFilter, the following exception occurs:

```
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot resolve PropertyFilter with id 'antPathFilter'; no FilterProvider configured
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:77) ~[jackson-databind-2.9.6.jar:2.9.6]
	at com.fasterxml.jackson.databind.SerializerProvider.reportBadDefinition(SerializerProvider.java:1191) ~[jackson-databind-2.9.6.jar:2.9.6]
	at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:312) ~[jackson-databind-2.9.6.jar:2.9.6]
	at com.fasterxml.jackson.databind.ser.std.StdSerializer.findPropertyFilter(StdSerializer.java:426) ~[jackson-databind-2.9.6.jar:2.9.6]
...
```

**Comment by Antibrumm** [comment]
Thanks for the info. I think I did not fall into this problem as I use an adapted version of the Readme. If you like you could give it a try and if that works for you too I will update the Readme?

```
/**
 * A specific {@link MappingJackson2HttpMessageConverter} that configures the given {@link ObjectMapper} with the
 * {@link AntPathFilterMixin}. This is needed only if we need multiple ObjectMappers.
 *
 * @author mfrey
 *
 */
public class AntPathFilterJackson2HttpMessageConverter extends MappingJackson2HttpMessageConverter {

    public AntPathFilterJackson2HttpMessageConverter(final ObjectMapper objectMapper) {
        super(objectMapper);
        ObjectMapper copy = objectMapper.copy();
        copy.addMixIn(Object.class, AntPathFilterMixin.class);
        setObjectMapper(copy);
    }

    @Override
    public boolean canWrite(final Class<?> clazz, final MediaType mediaType) {
        return AntPathFilterMappingJacksonValue.class.isAssignableFrom(clazz);
    }
}
```

```
@Configuration
public class WebConfig extends DelegatingWebMvcConfiguration {
 @Override
    public void configureMessageConverters(final List<HttpMessageConverter<?>> messageConverters) {
        // Add a MappingJackson2HttpMessageConverter so that
        // objectMapper.writeFiltered
        // is using the objectMapper configured with the needed Mixin

        messageConverters.add(new AntPathFilterJackson2HttpMessageConverter(objectMapper));

        //
        addDefaultHttpMessageConverters(messageConverters);
        super.configureMessageConverters(messageConverters);
    }
}

```


```
 @RequestMapping(value = "", method = RequestMethod.GET, produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseBody
    public AntPathFilterMappingJacksonValue list() throws JsonProcessingException {
        List<User> allUsers = userService.allUsers();
        return new AntPathFilterMappingJacksonValue(allUsers, "id", "login", "firstName", "lastName", "email",
                "currentRoles", "managedScopes.id", "managedScopes.label", "active");
    }
```

**Comment by mpscheidt** [comment]
That works fine! Thanks a lot for that.

Your project is very useful. I wonder why the Jackson library hasn't come up with such a feature yet.

A suggestion is to make the web config slightly more lightweight (so you don't need to explicitely deal with default message converters and super calls) by implementing the `WebMvcConfigurer` interface (instead of extending `DelegatingWebMvcConfiguration`):

```
@Configuration
public class WebMvcConfiguration implements WebMvcConfigurer {

	@Override
	public void extendMessageConverters(List<HttpMessageConverter<?>> converters) {
		converters.add(0, new AntPathFilterJackson2HttpMessageConverter(objectMapper));
	}
}
```

Apparently the `AntPathFilterJackson2HttpMessageConverter` needs to be added at the beginning at the list of message converters, in order to prevent the other message converters from feeling responsible before ` AntPathFilterJackson2HttpMessageConverter` gets its chance.

**Comment by Antibrumm** [comment]
Thanks for the feedback. Once i have time i update the readme.

I didnt know we can give the order of converters. This will simplify my setups alot :)
